### ISSUE TITLE
Problems compiling on MacOS

### ISSUE THREAD

**Issue by pauloney** [pkubowicz/opendetex#10]
This was reported by Ryan Schmidt from the MacPorts project  on 15 Aug 2011. They offer the patch at the ticket linked below. We should inform him at the closing of the ticket, so he can take this step out of the build.

FYI, there seems to be a problem compiling detex 2.8 with the clang compiler. The problem report is here: [Link to MacPorts ticket](https://trac.macports.org/ticket/30796)

-Ryan Schmidt for the MacPorts project
ryandesign@macports.org

**Comment by pkubowicz** [comment]
I doubt this is still applicable, as I compiled OpenDetex with the most recent Clang before releasing 2.8.2.

**Comment by pauloney** [comment]
This is one I could not test. I am not a Mac person...I'll inform the upstream and close the ticket.

**Comment by pauloney** [comment]
Upstream informed. Colsing ticket.
