### ISSUE TITLE
Default environments to add

### ISSUE THREAD

**Issue by pauloney** [pkubowicz/opendetex#3]
We should add this to the list of DEFAULTENV:

```
  {matrix}
  {bmatrix}
  {pmatrix}
  {vmatrix}
  {smallmatrix}
  {smallpmatrix}

  {wrapfigure}
  {figure}
  {floatfig}
  {floating}
  {psfrags}
  {pspicture}

  {algorithm}
  {align}
  {math}
  {displaymath}
  {tabbing}
  {split}
```

Line 68 of detex.l:

  `#define MAXENVS         10`

will have to be changed appropriately.

**Comment by pkubowicz** [comment]
Please note that I haven't added {figure}. I want to preserve some contents of the environment - contents of `\caption{}` (see contents of `test/` to see how it works correctly). Ideally I would like to preserve caption of {algorithm}, but for now it's easier to just ignore all contents of {algorithm} - I don't have time to do this properly.

**Comment by pauloney** [comment]
The ideal way to deal with this problem would be to save the contents of \caption of certain ENV (table, figure, algorithm, ...) or for that matter to save the contents of ANY \caption{} command no matter what environment it happened. What do you think? I could take this one on!

**Comment by pkubowicz** [comment]
Sure, if you know how to do it, I will be glad to incorporate your work.
