### ISSUE TITLE
Make Bug

### ISSUE THREAD

**Issue by Jadamso** [pkubowicz/opendetex#37]
I have the following issue on installation

[Jadamso@x1yoga2 opendetex]$ make
lex  detex.l
make: lex: Command not found
Makefile:115: recipe for target 'detex.c' failed
make: *** [detex.c] Error 127

Any help would be appreciated.

**Comment by pkubowicz** [comment]
Hello, see https://github.com/pkubowicz/opendetex/blob/master/INSTALL

You need a package providing the 'lex' program. Linux distributions have it in 'flex' package.

**Comment by Jadamso** [comment]
I had flex-devel installed but not flex. Thank you. That was the issue.
