### ISSUE TITLE
man page typo

### ISSUE THREAD

**Issue by kberry** [pkubowicz/opendetex#78]
Debian sent a trivial patch for the detex man page ...
```
--- texk/detex/detex-src/detex.man      (revision 64238)
+++ texk/detex/detex-src/detex.man      (working copy)
@@ -1,4 +1,4 @@
-.TH DETEX 1 "4 March 2021" "Purdue University"
+.TH DETEX 1 "30 August 2022" "Purdue University"
 .SH NAME
 detex \- a filter to strip \fITeX\fP commands from a .tex file.
 .SH SYNOPSIS
@@ -96,7 +96,7 @@ files.  Like \fITeX\fP, it interprets a leading or
 TEXINPUTS.  It does \fInot\fP support the `//' directory expansion magic seque$
 .PP
 Detex now handles the basic \fITeX\fP ligatures as a special case, replacing t$
-ligatures with acceptable charater substitutes.  This eliminates
+ligatures with acceptable character substitutes.  This eliminates
 spelling errors introduced by merely removing them.  The ligatures are
 \\aa, \\ae, \\oe, \\ss, \\o, \\l (and their upper-case
 equivalents).  The special "dotless" characters \\i and \\j are also
```

**Comment by kberry** [comment]
Here is another fix to the man page, to add a period after the sentence about Daniel, and not claim that detex is any kind of TeX interpreter.

```
--- detex-src/detex.man (revision 64397)
+++ detex-src/detex.man (working copy)
@@ -1,4 +1,4 @@
-.TH DETEX 1 "30 August 2022" "Purdue University"
+.TH DETEX 1 "15 September 2022" "TeX Live"
 .SH NAME
 detex \- a filter to strip \fITeX\fP commands from a .tex file.
 .SH SYNOPSIS
@@ -120,15 +120,17 @@ exceed the system's limit on the number of simulta
 .I Detex
 ignores unrecognized option characters after printing a warning message.
 .SH AUTHOR
-Originally written by Daniel Trinkle, Computer Science Department, Purdue University
+Originally written by Daniel Trinkle, Computer Science Department,
+Purdue University.
 .PP
 Maintained by Piotr Kubowicz <https://github.com/pkubowicz/opendetex>.
 .SH BUGS
 .I Detex
-is not a complete
+is not a
 .I TeX
-interpreter, so it can be confused by some constructs.
-Most errors result in too much rather than too little output.
+interpreter (it essentially reads the input with a (f)lex program), so
+it is easily confused by some constructs. Most errors result in too much
+rather than too little output.
 .PP
 Running \fILaTeX\fR
 source without a ``\\begin{document}''
```

**Comment by pkubowicz** [comment]
I'm not convinced this patch should change the copyright part. Same for #74. Patches should concentrate on fixing one thing, updating year is not fixing a typo.

Also, what is the sense of updating the date? Should the code be changed just because a new calendar year started?

**Comment by kberry** [comment]
With man pages, personally I update the date every time I change the
file. Otherwise there is too great a chance of the date failing to be
updated at the release.  So by updating the date, I thought I was
actually making less work for you.

But, of course, if you don't want to update the date, don't.
I know different people like to do things differently. --best, karl.

**Comment by kberry** [comment]
> Also, what is the sense of updating the date? Should the code be
> changed just because a new calendar year started?

Here you seem to be referring to actual code sources, not man pages?

For that, as always, there are different ways to do it. What I myself
mostly do is update the copyright year in a source file when it gets
some kind of "real" update.

However, many other programmers (almost all the core GNU packages) do
indeed update the copyright year of all source files in a package on
January 1, and that is also fine. Each way has pros and cons. -k
